# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, verbose_name='\u6807\u9898')),
                ('content', models.TextField(db_index=True, max_length=500, verbose_name='\u5185\u5bb9')),
                ('category', models.CharField(max_length=256, verbose_name='\u5206\u7c7b')),
                ('published_date', models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('update_date', models.DateTimeField(verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
